"""added is_staff column

Revision ID: 9f04cb428a74
Revises: 56c65a54cc41
Create Date: 2021-05-16 22:46:20.879552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f04cb428a74'
down_revision = '56c65a54cc41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_staff', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_staff')
    # ### end Alembic commands ###
